<a href="https://colab.research.google.com/github/ReshamWadhwa/ML-models/blob/main/src/models/logistic_regression/code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
data = pd.read_csv("suv_data.csv")
data.shape

(400, 5)

In [3]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:

data = pd.concat([data, pd.get_dummies(data['Gender'], drop_first=True, prefix="gender")], 1)

In [5]:
data.drop('User ID', axis = 1, inplace = True)
data.describe()


Age  EstimatedSalary   Purchased  gender_Male
count  400.000000       400.000000  400.000000   400.000000
mean    37.655000     69742.500000    0.357500     0.490000
std     10.482877     34096.960282    0.479864     0.500526
min     18.000000     15000.000000    0.000000     0.000000
25%     29.750000     43000.000000    0.000000     0.000000
50%     37.000000     70000.000000    0.000000     0.000000
75%     46.000000     88000.000000    1.000000     1.000000
max     60.000000    150000.000000    1.000000     1.000000

In [6]:
# X = data[['Age','EstimatedSalary','gender_Male']]
X = data.iloc[:,[1,2]].values
Y = data['Purchased']
X_train, X_test, y_train, y_test =  train_test_split(X, Y, test_size = 0.25, random_state = 1)

In [7]:
X_train

array([[    20,  49000],
       [    46,  88000],
       [    31,  34000],
       [    47,  30000],
       [    35,  50000],
       [    39,  96000],
       [    33, 113000],
       [    49,  86000],
       [    45,  79000],
       [    44,  39000],
       [    41,  59000],
       [    42,  53000],
       [    35,  73000],
       [    41,  72000],
       [    27,  96000],
       [    30, 116000],
       [    41,  52000],
       [    41,  52000],
       [    20,  82000],
       [    46,  41000],
       [    27,  31000],
       [    35,  71000],
       [    49,  28000],
       [    35,  91000],
       [    37,  75000],
       [    32, 117000],
       [    36,  75000],
       [    20,  86000],
       [    38,  50000],
       [    49,  36000],
       [    40,  65000],
       [    37,  77000],
       [    60,  46000],
       [    48, 138000],
       [    40,  71000],
       [    36,  63000],
       [    26,  81000],
       [    33,  31000],
       [    41,  51000],
       [    46,  74000],


In [8]:
X_test

array([[    36,  33000],
       [    39,  61000],
       [    36, 118000],
       [    39, 122000],
       [    26, 118000],
       [    38,  65000],
       [    20,  36000],
       [    49,  89000],
       [    31,  18000],
       [    48, 141000],
       [    34,  72000],
       [    39,  73000],
       [    35,  72000],
       [    48, 131000],
       [    53,  82000],
       [    56, 133000],
       [    60,  83000],
       [    27,  58000],
       [    28,  87000],
       [    60, 102000],
       [    40,  75000],
       [    50,  88000],
       [    44, 139000],
       [    47,  43000],
       [    45,  26000],
       [    26,  15000],
       [    58,  47000],
       [    49,  74000],
       [    53,  34000],
       [    52, 114000],
       [    39,  42000],
       [    19,  76000],
       [    18,  86000],
       [    57,  74000],
       [    27,  84000],
       [    30,  80000],
       [    22,  18000],
       [    32,  86000],
       [    50,  20000],
       [    19,  25000],


In [13]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [47]:
lr_library = LogisticRegression(verbose=True, penalty='none')
lr_library.fit(X=X_train, y=y_train)
y_pred1 = lr_library.predict(X_test)

print(lr_library.coef_)
print(classification_report(y_test, y_pred1))

confusion_matrix(y_test, y_pred1)

[[2.47691272e-01 4.56688937e-05]]
              precision    recall  f1-score   support

           0       0.84      0.90      0.87        58
           1       0.84      0.76      0.80        42

    accuracy                           0.84       100
   macro avg       0.84      0.83      0.83       100
weighted avg       0.84      0.84      0.84       100



[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


array([[52,  6],
       [10, 32]])

              precision    recall  f1-score   support

           0       0.84      0.90      0.87        58
           1       0.84      0.76      0.80        42

    accuracy                           0.84       100
   macro avg       0.84      0.83      0.83       100
weighted avg       0.84      0.84      0.84       100



[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


array([[52,  6],
       [10, 32]])

In [16]:
#### LOGISTIC REGRESSION WITHOUT LIBRARY

In [68]:
import math
import random
class LogisticRegression2:
  learning_rate= None
  X = None
  Y = None
  m = None # training smaples
  n = None # Number of training features
  iterations = None
  W = None
  b = None
  loss = None
  loss_bias = None
  lce = None

  def __init__(self, learning_rate=0.00001, iterations=10000):
    self.learning_rate=learning_rate
    self.iterations = iterations

  def initialise_parameters(self):
      self.W = np.zeros(self.n)
      self.W = np.random.uniform(-1, 1, self.n)
      self.b = 0
      print(self.m, self.n, self.W, self.b)

  def sigmoid(self,x):
    x = -1*x
    e = np.exp(x)
    return 1/(1+e)
    
  def predict_prob(self, X):
      return self.sigmoid(np.dot(X, self.W)+self.b)
    
  def predict(self, X, threshold=0.5):
      return self.predict_prob(X) >= threshold


  def fit(self,X,Y):
      self.X = X
      self.Y = Y
      self.m, self.n = X.shape #if len(X.shape)>1 else X.shape[0],1

      self.initialise_parameters()
      print(self.X.T.shape)
      print(self.W.shape)

      for i in range( self.iterations ) :
          h = self.predict_prob(X)
          error = h-self.Y
          gradient_w = np.dot(X.T, error) / self.m
          gradient_b = np.dot(np.ones(self.Y.shape).T,error) / self.m

          self.W -= self.learning_rate * gradient_w
          self.b -= self.learning_rate * gradient_b
          
          if i%1000==0:   
            print("Iteration ",i, "W:",self.W,", b:",self.b) 
          # self.update_weights()
      return self
  

In [69]:
lr2 = LogisticRegression2(learning_rate=0.01, iterations=100000)
lr2.fit(X=X_train, Y=y_train)
y_pred2 = lr2.predict(X_test)

print(classification_report(y_test, y_pred2))

confusion_matrix(y_test, y_pred2)

300 2 [-0.97574916 -0.25534129] 0
(2, 300)
(2,)
Iteration  0 W: [ -0.82218249 297.74465871] , b: 0.0033666666666666667


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:28: RuntimeWarning: overflow encountered in exp


Iteration  1000 W: [ -7.68591582 275.34465871] , b: -0.9499666666666831
Iteration  2000 W: [-14.48631544 291.91165771] , b: -1.901833321720941
Iteration  3000 W: [-21.35004877 269.51165771] , b: -2.855166655054319
Iteration  4000 W: [-28.2137821  247.11165771] , b: -3.808499988387709
Iteration  5000 W: [-35.04035031 244.5773124 ] , b: -4.760966699521099
Iteration  6000 W: [-41.90408364 222.1773124 ] , b: -5.714300032854489
Iteration  7000 W: [-48.76781698 199.7773124 ] , b: -6.667633366187879
Iteration  8000 W: [-55.63155031 177.3773124 ] , b: -7.620966699521269
Iteration  9000 W: [-62.49528364 154.9773124 ] , b: -8.574300032854659
Iteration  10000 W: [-69.22283424 257.31932137] , b: -9.524200525284211
Iteration  11000 W: [-76.0566678  250.15251392] , b: -10.476867196805765
Iteration  12000 W: [-82.92040114 227.75251392] , b: -11.430200530139155
Iteration  13000 W: [-89.78413447 205.35251392] , b: -12.383533863472545
Iteration  14000 W: [-96.61860794 197.79909982] , b: -13.336213866257

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[ 0, 58],
       [ 0, 42]])

In [46]:
lr2.predict_prob(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: RuntimeWarning: overflow encountered in exp


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
y_pred_2 = lr_wo_library.predict(X_test)
y_pred_2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: RuntimeWarning: overflow encountered in exp


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
class LogisticRegression3:
    verbose = True
    def __init__(self, lr=0.01, num_iter=100000, fit_intercept=True, verbose=False):
        self.lr = lr
        self.num_iter = num_iter
        self.fit_intercept = fit_intercept
    
    def __add_intercept(self, X):
        intercept = np.ones((X.shape[0], 1))
        return np.concatenate((intercept, X), axis=1)
    
    def __sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

  
    def __loss(self, h, y):
        print(y[0],h[0])
        n = (-y * np.log(h) - (1 - y) * np.log(1 - h))
        # print(n.shape)
        # print("n : ",n,"loss - n.mean() : ",n.mean())
        return n.mean()
    
    def fit(self, X, y):
        if self.fit_intercept:
            X = self.__add_intercept(X)
        
        # weights initialization
        self.theta = np.zeros(X.shape[1])
        
        for i in range(self.num_iter):
            z = np.dot(X, self.theta)
            h = self.__sigmoid(z)
            gradient = np.dot(X.T, (h - y)) / y.size
            self.theta -= self.lr * gradient
            
            if(self.verbose == True and i%50==0):
                print("Iteration ",i, "W:",self.theta) 
                z = np.dot(X, self.theta)
                h = self.__sigmoid(z)
                print(f'loss: {self.__loss(h, y)} \t')
    
    def predict_prob(self, X):
        if self.fit_intercept:
            X = self.__add_intercept(X)
    
        return self.__sigmoid(np.dot(X, self.theta))
    
    def predict(self, X, threshold):
        return self.predict_prob(X) >= threshold

In [ ]:
lr3 = LogisticRegression3(num_iter = 1000)

In [ ]:
lr3.fit(X_train, y_train)

Iteration  0 W: [-1.63333333e-03 -3.21166667e-02 -4.69333333e+01]
0 0.0
loss: inf 	
Iteration  50 W: [-5.3300e-02 -5.2385e-01 -3.2400e+02]
0 0.0
loss: inf 	
Iteration  100 W: [-0.09496667 -0.64421667 88.8       ]
0 1.0
loss: inf 	
Iteration  150 W: [-1.46633333e-01 -1.13595000e+00 -1.88266667e+02]
0 0.0
loss: inf 	
Iteration  200 W: [-1.88300000e-01 -1.25631667e+00  2.24533333e+02]
0 1.0
loss: inf 	
Iteration  250 W: [ -0.23996667  -1.74805    -52.53333333]
0 0.0
loss: inf 	
Iteration  300 W: [-2.91633333e-01 -2.23978333e+00 -3.29600000e+02]
0 0.0
loss: inf 	
Iteration  350 W: [-0.3333  -2.36015 83.2    ]
0 1.0
loss: inf 	
Iteration  400 W: [  -0.38496667   -2.85188333 -193.86666667]
0 0.0
loss: inf 	
Iteration  450 W: [ -0.42663333  -2.97225    218.93333333]
0 1.0
loss: inf 	
Iteration  500 W: [ -0.4783      -3.46398333 -58.13333333]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in exp
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: RuntimeWarning: divide by zero encountered in log


0 0.0
loss: inf 	
Iteration  550 W: [  -0.52996667   -3.95571667 -335.2       ]
0 0.0
loss: inf 	
Iteration  600 W: [-0.57163333 -4.07608333 77.6       ]
0 1.0
loss: inf 	
Iteration  650 W: [  -0.6233       -4.56781667 -199.46666667]
0 0.0
loss: inf 	
Iteration  700 W: [ -0.66496667  -4.68818333 213.33333333]
0 1.0
loss: inf 	
Iteration  750 W: [ -0.71663333  -5.17991667 -63.73333333]
0 0.0
loss: inf 	
Iteration  800 W: [  -0.7683    -5.67165 -340.8    ]
0 0.0
loss: inf 	
Iteration  850 W: [-0.80996667 -5.79201667 72.        ]
0 1.0
loss: inf 	
Iteration  900 W: [  -0.86163333   -6.28375    -205.06666667]
0 0.0
loss: inf 	
Iteration  950 W: [ -0.9033      -6.40411667 207.73333333]
0 1.0
loss: inf 	


In [ ]:
y_pred_3 = lr3.predict(X_test, threshold=0.5)
y_pred_3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_3)

array([[ 0, 58],
       [ 0, 42]])