<a href="https://colab.research.google.com/github/ReshamWadhwa/ML-models/blob/logit/src/models/logistic_regression/code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np

In [8]:
data = pd.read_csv("suv_data.csv")
data.shape

(400, 5)

In [4]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [14]:

data = pd.concat([data, pd.get_dummies(data['Gender'], drop_first=True, prefix="gender")], 1)

In [49]:
data.drop('User ID', axis = 1, inplace = True)
data.describe()


Age  EstimatedSalary   Purchased  gender_Male
count  400.000000       400.000000  400.000000   400.000000
mean    37.655000     69742.500000    0.357500     0.490000
std     10.482877     34096.960282    0.479864     0.500526
min     18.000000     15000.000000    0.000000     0.000000
25%     29.750000     43000.000000    0.000000     0.000000
50%     37.000000     70000.000000    0.000000     0.000000
75%     46.000000     88000.000000    1.000000     1.000000
max     60.000000    150000.000000    1.000000     1.000000

In [62]:
# X = data[['Age','EstimatedSalary','gender_Male']]
X = data.iloc[:,[1,2]].values
Y = data['Purchased']
X_train, X_test, y_train, y_test =  train_test_split(X, Y, test_size = 0.25, random_state = 1)

In [63]:
X_train

array([[    20,  49000],
       [    46,  88000],
       [    31,  34000],
       [    47,  30000],
       [    35,  50000],
       [    39,  96000],
       [    33, 113000],
       [    49,  86000],
       [    45,  79000],
       [    44,  39000],
       [    41,  59000],
       [    42,  53000],
       [    35,  73000],
       [    41,  72000],
       [    27,  96000],
       [    30, 116000],
       [    41,  52000],
       [    41,  52000],
       [    20,  82000],
       [    46,  41000],
       [    27,  31000],
       [    35,  71000],
       [    49,  28000],
       [    35,  91000],
       [    37,  75000],
       [    32, 117000],
       [    36,  75000],
       [    20,  86000],
       [    38,  50000],
       [    49,  36000],
       [    40,  65000],
       [    37,  77000],
       [    60,  46000],
       [    48, 138000],
       [    40,  71000],
       [    36,  63000],
       [    26,  81000],
       [    33,  31000],
       [    41,  51000],
       [    46,  74000],


In [64]:
X_test

array([[    36,  33000],
       [    39,  61000],
       [    36, 118000],
       [    39, 122000],
       [    26, 118000],
       [    38,  65000],
       [    20,  36000],
       [    49,  89000],
       [    31,  18000],
       [    48, 141000],
       [    34,  72000],
       [    39,  73000],
       [    35,  72000],
       [    48, 131000],
       [    53,  82000],
       [    56, 133000],
       [    60,  83000],
       [    27,  58000],
       [    28,  87000],
       [    60, 102000],
       [    40,  75000],
       [    50,  88000],
       [    44, 139000],
       [    47,  43000],
       [    45,  26000],
       [    26,  15000],
       [    58,  47000],
       [    49,  74000],
       [    53,  34000],
       [    52, 114000],
       [    39,  42000],
       [    19,  76000],
       [    18,  86000],
       [    57,  74000],
       [    27,  84000],
       [    30,  80000],
       [    22,  18000],
       [    32,  86000],
       [    50,  20000],
       [    19,  25000],


In [65]:
lr_library = LogisticRegression()

In [66]:
lr_library.fit(X=X_train, y=y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [67]:
y_pred = lr_library.predict(X_test)

In [68]:
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0])

In [69]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87        58
           1       0.84      0.76      0.80        42

    accuracy                           0.84       100
   macro avg       0.84      0.83      0.83       100
weighted avg       0.84      0.84      0.84       100



In [70]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[52,  6],
       [10, 32]])

In [71]:
#### LOGISTIC REGRESSION WITHOUT LIBRARY

In [74]:
import math

class LogisticRegression_wo_lib:
  learning_rate= None
  X = None
  Y = None
  m = None # training smaples
  n = None # Number of training features
  iterations = None
  W = None
  b = None
  loss = None
  loss_bias = None
  lce = None

  def __init__(self, learning_rate=0.01, iterations=1000):
    self.learning_rate=learning_rate
    self.iterations = iterations

  def initialise_parameters(self):
      self.W = np.zeros(self.n)
      self.b = 0

  def sigmoid(self,x):
    x = -1*x
    e = np.exp(x)
    return 1/(1+e)
    
  
  def fit(self,X,Y):
      self.X = X
      self.Y = Y
      self.m, self.n = X.shape if len(X.shape)>1 else X.shape[0],1

      self.initialise_parameters()

      for i in range( self.iterations ) :
          lin_sum = np.dot(X.T, self.W)+self.b
          h = self.sigmoid(lin_sum)
          gradient = np.dot(X.T, (h - Y)) / Y.size

          self.W -= self.learning_rate * gradient
            
          if i%50==0:   
            print("Iteration ",i, "W:",self.W,", b:",self.b," Loss : ", self.loss, "Loss bias : ", self.loss_bias, "log loss:", self.lce) 
          self.update_weights()
      return self
  

In [75]:
lr_wo_library = LogisticRegression_wo_lib()

In [79]:
X_train.shape

(300, 2)

In [78]:
lr_wo_library.fit(X_train,y_train)

ValueError: ignored